version: '3.4'

services:
  dev-center:
    image: ${DOCKER_REGISTRY-}dev-center
    build:
      context: .
      dockerfile: src/Http.API/Dockerfile
  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=root