global using System;
global using System.Linq.Expressions;
global using System.Net;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Json;
global using Core.Entities;
global using Core.Models;
global using Core.Utils;
global using EntityFramework;
global using Http.Application.Implement;
global using Http.Application.Interface;
// global using EntityFramework;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
// global using Core.Identity;
global using Share.Models;
global using Http.Application.Manager;
global using Http.Application.IManager;
global using Http.Application.QueryStore;
global using Http.Application.CommandStore;
