version: "1"
networks:
  devCenter:
services:
  dev-center:
    image: niltor/dev-center:latest
    ports:
      - "9161:80"
    environment:
      ConnectionStrings__Default: "Server=db;Port=5432;Database=DevCenter;User Id=postgres;password=root;"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devCenter

  db:
    image: postgres:15.1-alpine
    command:
      - -i
      # ports:
      # - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"

    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 3s
      timeout: 2s
      retries: 5
    networks:
      - devCenter
