global using Core.Models;
global using Core.Utils;
global using EntityFramework;
global using Http.Application.DataStore;
global using Http.Application.Interface;
global using Http.Application.Services;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
// global using Core.Identity;
global using Share.Models;
//global using OpenIddict.Validation.AspNetCore;
global using System.Text.Json.Serialization;