global using Core.Models;
global using Core.Utils;
global using EntityFramework;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
//global using OpenIddict.Validation.AspNetCore;
global using System.Text.Json.Serialization;
global using Http.Application.Services;